name: Coverage (base branch)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  coverage-base:
    uses: ./.github/workflows/coverage-base-compute.yml
    with:
      lookup-only: true
